name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '10.0.x'

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore
      working-directory: Source

    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: Source

    - name: Test with coverage
      run: dotnet test --configuration Release --no-build --collect:"XPlat Code Coverage" --results-directory ../TestResults
      working-directory: Source

    - name: Upload coverage
      if: always()
      uses: actions/upload-artifact@v7
      with:
        name: coverage-report
        path: TestResults/*/coverage.cobertura.xml

  build:
    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    needs: test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
        - os: macos-latest
          RUNTIMEID: osx-x64
        - os: ubuntu-latest
          RUNTIMEID: linux-x64
        - os: windows-latest
          RUNTIMEID: win-x64

    steps:
    - uses: actions/checkout@v6
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Publish
      run: dotnet publish WebsiteValidator/WebsiteValidator.csproj -c Release -o publish -p:PublishReadyToRun=true --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:UseAppHost=true -r ${{matrix.RUNTIMEID}}
      working-directory: Source
